### ISSUE TITLE
Edit react native code remotely

### ISSUE THREAD

**Issue by adamelk** [hharnisc/react-native-meteor-websocket-polyfill#1]
I am currently using Meteor, Famous, and phonegap, and the biggest advantage is being able to push updates to our app without going through the App Store approval process.  

I am currently contemplating switching to react native. My question is if there is any way to edit react native code outside of the Xcode project, so you could essentially update the native app without going through the App Store?

**Comment by garethdown44** [comment]
Suggest posting this question on the react native github project or stackoverflow.

**Comment by hharnisc** [comment]
good suggestion @garethdown44 - @adamelk I would post there too. I know that Apple has rules around how you can do hot code pushes. React Native is new enough that you might find yourself in a grey area, but it's hard to say :)
