### ISSUE TITLE
Subscribing to "todos" doesn't work (but lists does)

### ISSUE THREAD

**Issue by garethdown44** [hharnisc/react-native-meteor-websocket-polyfill#2]
Hi - I was trying your project out and I found that I was able to subscribe to publicLists/privateLists as in your example, but when I try to subscribe to "todos" and observe the todos collection, nothing happens.

I wonder if it's an issue with passing in a parameter?

I have forked and made an example here: https://github.com/garethdown44/react-native-meteor-websocket-polyfill.git

If you could let me know if it's a bug in your code, or something I am doing wrong I would really appreciate it.

Thanks

**Comment by garethdown44** [comment]
Found what I was doing wrong, the params must be an array.

**Comment by hharnisc** [comment]
Ah I see, glad you figured it out!
