### ISSUE TITLE
Use of Meteor front-end packages?

### ISSUE THREAD

**Issue by sunny-g** [hharnisc/react-native-meteor-websocket-polyfill#3]
I'm assuming that since this package doesn't use the native Meteor `ddp` and `minimongo` packages just yet, we also won't be able to use any `accounts-` packages or any others that rely on DOM. 

Is this correct? Are DOM polyfills the only thing blocking developers from using the client-side parts of Meteor's packages with react-native?

**Comment by hharnisc** [comment]
Hey @sunny-g, you're correct the DOM polyfills are the biggest thing missing right now. Though there has been some chatting in the community of client side builds that don't include references to the DOM, it's not something that has been implemented by MDG _yet_.

I've also tried using packaging the backend scripts for DDP and minimongo without any luck. Building out at DOM would be a nice thing to have, as I'm sure more than just the Meteor community would like to have it!

**Comment by sunny-g** [comment]
Hey @hharnisc, thanks for getting back to me! I'm surprised that no one has written a blank "canvas" `document` object that just doesn't do anything... I haven't thought about it much but I could imagine that you could take that empty `document` and then write wrapper code (for say, React Native) that lets client-side code call custom, stubbed DOM methods that (under the hood) manipulate the underlying iOS component structure rather than the actual DOM. 

For example, after importing your react-native-dom-stub, calling `document.getElementsByTagName('Image')` will return you an array of <Image> components.

Something to think about, unless you see something totally wrong with that thought process...
