### ISSUE TITLE
How to do CRUD operations on the subscription.

### ISSUE THREAD

**Issue by sandcforge** [hharnisc/react-native-meteor-websocket-polyfill#5]
Hi,
This is the great work to glue both react-native and Meteor. And the example works smoothly.
Right now The react-native app can display the list reactively, once the list is CRUD by other web front-end. I am wondering how I can do this on the react-native app. Would you please give me a short example?

Thanks,
Chen

**Comment by tvogels** [comment]
One option would be to use methods to accomplish this. You could create an 'editSomething' method in your Meteor backend and call it with `ddpClient.call('editSomething', ...)`. With this approach you would have to take care of latency compensation yourself.

**Comment by sandcforge** [comment]
Hi tvogels,
Thanks for your response.
Yes, This is what I have done right now.

Chen
